import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, Link, useActionData, useLoaderData } from "react-router";

import { DataTable, MoneylessBadge, SetupBanner } from "../components/KitUi";
import { requireOperationsKitContext } from "../lib/app-context.server";
import {
  assignPreferredSuppliersToNeeds,
  createPurchaseOrderFromNeed,
  createPurchaseOrdersFromReadyNeeds,
  loadPurchaseNeeds,
  loadPurchaseOrderDetail,
  loadPurchaseOrders,
  transitionPurchaseOrder,
} from "../lib/operations-kit.server";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const context = await requireOperationsKitContext(request);
  if (!context.configured) return { configured: false, setupError: context.setupError };

  const url = new URL(request.url);
  const purchaseOrderId = url.searchParams.get("purchaseOrderId");

  return {
    configured: true,
    needs: await loadPurchaseNeeds(context.pool, context.ctx.tenantId),
    purchaseOrders: await loadPurchaseOrders(context.pool, context.ctx.tenantId),
    purchaseOrderDetail: purchaseOrderId
      ? await loadPurchaseOrderDetail(context.pool, context.ctx.tenantId, purchaseOrderId)
      : null,
  };
};

export const action = async ({ request }: ActionFunctionArgs) => {
  const context = await requireOperationsKitContext(request);
  if (!context.configured) return { message: context.setupError };

  const form = await request.formData();
  const intent = String(form.get("intent"));

  if (intent === "assignPreferred") {
    await assignPreferredSuppliersToNeeds(context.pool, context.ctx.tenantId);
    return {
      message: "Preferred suppliers assigned. Next: create draft purchase orders.",
    };
  }

  if (intent === "createPo") {
    const result = await createPurchaseOrdersFromReadyNeeds(
      context.pool,
      context.ctx.tenantId,
    );
    return {
      message: `${result.purchaseOrderIds.length} purchase order draft(s) created or reused. Open a PO to move it through the lifecycle.`,
    };
  }

  if (intent === "createPoForNeed") {
    const result = await createPurchaseOrderFromNeed(
      context.pool,
      context.ctx.tenantId,
      String(form.get("purchaseNeedId")),
    );
    return {
      message: result.purchaseOrderId
        ? "Purchase order draft created for this need."
        : "Purchase need was not open.",
    };
  }

  if (intent === "poStatus") {
    await transitionPurchaseOrder(
      context.pool,
      context.ctx.tenantId,
      String(form.get("purchaseOrderId")),
      String(form.get("status")) as
        | "pending_approval"
        | "approved"
        | "sent"
        | "acknowledged"
        | "cancelled",
    );
    return { message: "Purchase order status updated." };
  }

  return { message: "No action was performed." };
};

export default function Procurement() {
  const data = useLoaderData<typeof loader>();
  const actionData = useActionData<typeof action>();
  if (!data.configured || !("needs" in data)) {
    return <SetupBanner message={data.setupError ?? "Database setup is incomplete."} />;
  }

  return (
    <s-page heading="Procurement">
      <s-section>
        <s-paragraph>
          Purchase needs are generated by committed MRP runs. Preferred
          suppliers turn shortages into draft purchase orders inside Operations
          Kit. Procurement prepares drafts; Procurement Manager approves before
          the PO can be sent and acknowledged.
        </s-paragraph>
        {actionData?.message ? (
          <s-box padding="base" borderWidth="base" borderRadius="base">
            <s-paragraph>{actionData.message}</s-paragraph>
          </s-box>
        ) : null}
      </s-section>

      <s-section heading="Purchase needs board">
        <DataTable
          headings={["Item", "Quantity", "Preferred supplier", "Assigned supplier", "Status", "Purchase order", "Action"]}
          rows={(data.needs ?? []).map((need: any) => [
            <strong>
              {need.sku} {need.title}
            </strong>,
            `${Number(need.quantity).toLocaleString()} ${need.unit}`,
            need.preferred_supplier_name ?? "No preferred supplier",
            need.supplier_name ?? "Missing supplier",
            <MoneylessBadge
              tone={need.status === "converted_to_po" ? "success" : need.status === "open" ? "warning" : "info"}
            >
              {need.status}
            </MoneylessBadge>,
            need.purchase_order_id ? (
              <Link to={`/app/procurement?purchaseOrderId=${need.purchase_order_id}`}>
                {need.purchase_order_number}
              </Link>
            ) : (
              "Not converted"
            ),
            need.purchase_order_id ? (
              "Converted"
            ) : (
              <Form method="post">
                <input type="hidden" name="intent" value="createPoForNeed" />
                <input type="hidden" name="purchaseNeedId" value={need.id} />
                <s-button variant="primary" type="submit">Create PO</s-button>
              </Form>
            ),
          ])}
        />
      </s-section>

      <s-section heading="Purchase orders">
        <DataTable
          headings={["PO", "Supplier", "Status", "Lines", "Action"]}
          rows={(data.purchaseOrders ?? []).map((po: any) => [
            <Link to={`/app/procurement?purchaseOrderId=${po.id}`}>
              <strong>{po.display_number}</strong>
            </Link>,
            po.supplier_name,
            <MoneylessBadge
              tone={po.status === "acknowledged" ? "success" : po.status === "sent" ? "info" : "warning"}
            >
              {po.status}
            </MoneylessBadge>,
            po.line_count,
            <s-stack direction="inline" gap="small">
              {po.status === "draft" ? (
                <Form method="post">
                  <input type="hidden" name="intent" value="poStatus" />
                  <input type="hidden" name="purchaseOrderId" value={po.id} />
                  <input type="hidden" name="status" value="pending_approval" />
                  <s-button type="submit">Submit</s-button>
                </Form>
              ) : null}
              {po.status === "pending_approval" ? (
                <Form method="post">
                  <input type="hidden" name="intent" value="poStatus" />
                  <input type="hidden" name="purchaseOrderId" value={po.id} />
                  <input type="hidden" name="status" value="approved" />
                  <s-button variant="primary" type="submit">Approve</s-button>
                </Form>
              ) : null}
              {po.status === "approved" ? (
                <Form method="post">
                  <input type="hidden" name="intent" value="poStatus" />
                  <input type="hidden" name="purchaseOrderId" value={po.id} />
                  <input type="hidden" name="status" value="sent" />
                  <s-button variant="primary" type="submit">Send</s-button>
                </Form>
              ) : null}
              {po.status === "sent" ? (
                <Form method="post">
                  <input type="hidden" name="intent" value="poStatus" />
                  <input type="hidden" name="purchaseOrderId" value={po.id} />
                  <input type="hidden" name="status" value="acknowledged" />
                  <s-button variant="primary" type="submit">Acknowledge</s-button>
                </Form>
              ) : null}
              {po.status === "acknowledged" ? <s-link href="/app/receiving">Receive</s-link> : null}
            </s-stack>,
          ])}
        />
      </s-section>

      {data.purchaseOrderDetail?.order ? (
        <s-section heading={`Purchase order ${data.purchaseOrderDetail.order.display_number}`}>
          <s-box padding="base" borderWidth="base" borderRadius="base">
            <s-stack direction="block" gap="small">
              <s-heading>
                {data.purchaseOrderDetail.order.supplier_name} ·{" "}
                {data.purchaseOrderDetail.order.status}
              </s-heading>
              <s-paragraph>
                Lifecycle: Draft → Procurement Manager approval → Sent →
                Acknowledged → Receiving/QC.
              </s-paragraph>
              <s-stack direction="inline" gap="small">
                <Form method="post">
                  <input type="hidden" name="intent" value="poStatus" />
                  <input
                    type="hidden"
                    name="purchaseOrderId"
                    value={data.purchaseOrderDetail.order.id}
                  />
                  <input type="hidden" name="status" value="pending_approval" />
                  <s-button type="submit">Submit for approval</s-button>
                </Form>
                <Form method="post">
                  <input type="hidden" name="intent" value="poStatus" />
                  <input
                    type="hidden"
                    name="purchaseOrderId"
                    value={data.purchaseOrderDetail.order.id}
                  />
                  <input type="hidden" name="status" value="approved" />
                  <s-button variant="primary" type="submit">
                    Procurement Manager approve
                  </s-button>
                </Form>
                <Form method="post">
                  <input type="hidden" name="intent" value="poStatus" />
                  <input
                    type="hidden"
                    name="purchaseOrderId"
                    value={data.purchaseOrderDetail.order.id}
                  />
                  <input type="hidden" name="status" value="sent" />
                  <s-button type="submit">Send to supplier</s-button>
                </Form>
                <Form method="post">
                  <input type="hidden" name="intent" value="poStatus" />
                  <input
                    type="hidden"
                    name="purchaseOrderId"
                    value={data.purchaseOrderDetail.order.id}
                  />
                  <input type="hidden" name="status" value="acknowledged" />
                  <s-button type="submit">Supplier acknowledged</s-button>
                </Form>
              </s-stack>
            </s-stack>
          </s-box>
          <DataTable
            headings={["Line item", "Quantity", "Lead time", "Expected", "Status"]}
            rows={data.purchaseOrderDetail.lines.map((line: any) => [
              <strong>
                {line.sku} {line.title}
              </strong>,
              `${Number(line.quantity).toLocaleString()} ${line.unit}`,
              `${line.lead_time_days ?? 7} days`,
              line.expected_delivery_date
                ? new Date(line.expected_delivery_date).toLocaleDateString()
                : "Not set",
              line.status,
            ])}
          />
        </s-section>
      ) : null}
    </s-page>
  );
}
